import time
while True:
    time.sleep(0.75)
    print("                                臧一凡      ")
    print("")
    print("                             00000   00000   ")
    print("                            0     0 0     0  ")
    print("                            0  ❀   0  ❀   0  ")
    print("                             0  在一起   0   ")
    print("                              0         0    ")
    print("                                0 ❀   0      ")
    print("                                  0 0        ")
    print("                                 赵婷婷      ")
    print("")
    print("")
    time.sleep(0.75)
    print("             我")
    print("")
    time.sleep(0.5)
    print("             爱")
    print("")
    time.sleep(0.5)
    print("             你")
    print("")
    time.sleep(0.25)
    print("                 L      OOOOO  V     V  EEEEE")  
    print("                 L      O   O  V     V  E    ")
    print("                 L      O   O   V   V   EEEEE")
    print("                 L      O   O    V V    E    ")
    print("                 LLLLL  OOOOO     V     EEEEE")      
    print("")
    print("")    

